### ISSUE TITLE
Refactor parameters to use OrderdedDictionary swift-collections

### ISSUE THREAD

**Issue by onmyway133** [onmyway133/Swiftlane#52]
OrderedDictionary from https://swift.org/blog/swift-collections/ ensures order while allowing us to change any parameter

**Comment by Frederiks96** [comment]
This sounds good. Can we encounter any flags that don't require a value? 

I.e. for xcodebuild, from what I understand, it is possible to pass build flags using `setting=value`, which doesn't follow the normal `-key value` argument format. There are probably more examples like this. So I guess users won't be able to set values using a dictionary like this. For xcodebuild, we could expose another (ordered) dictionary for build settings to pass in the format of `setting=value` after the `(build|test|archive|build-for-testing|test-without-building)`

**Comment by onmyway133** [comment]
There can be some variants

```
-key value
-- key value
key=value
just_key
-key=value
```

That's why I changed from initial DIctionary to Array as for now. Maybe we can just use OrderedSet or just Set
