### ISSUE TITLE
Use async await 

### ISSUE THREAD

**Issue by onmyway133** [onmyway133/Swiftlane#54]
Follow https://github.com/apple/swift-evolution/blob/main/proposals/0296-async-await.md

For now I have a simple Sequence/Pararelle mechanism to schedule Task. Can consider Combine but that must work on Linux and CI too.

Async await makes writing async task a breeze

**Comment by Frederiks96** [comment]
This would be pretty cool. Will this require users of Puma to run Swift 5.5+?
